spring:
  # This setting tells JPA to automatically create or update your database schema 
  # based on your Java entity classes. It's very useful for development.
  jpa:
    hibernate:
      ddl-auto: update

